### ISSUE TITLE
Arabic Language Support

### ISSUE THREAD

**Issue by MichelleMa8** [ariebovenberg/pdfje#83]
Hi, 

First of all, I'd like to express my gratitude and appreciation for the work you've put into this project. It's truly impressive and provides a valuable resource.

I have been using your project and I'm quite excited about the features it offers. However, I couldn't find information about Arabic language support. I'm particularly interested in generating pdf in Arabic.

Could you please clarify whether this project supports the Arabic language or if there are plans to include Arabic language support in the future?

If Arabic language support is not currently available, I would like to understand if there's a roadmap or any guidance on how one might contribute to adding this functionality.

Thank you again for your hard work, and I'm looking forward to your response.

**Comment by ariebovenberg** [comment]
Hi @MichelleMa8, thanks for taking the time to open this issue. At the moment, Arabic is not supported because pdfje is still a one-person (me) project and I don't have the knowledge to implement it. I don't expect it to be in the roadmap anytime soon. 

What I do know is that Arabic glyphs in fonts should be supported, but there's probably a lot more to rendering Arabic text properly.

My suggestion would be to have a look at fpdf2, which has a large (international) community, and they explicitly mention Arabic [here](https://py-pdf.github.io/fpdf2/Unicode.html#right-to-left-arabic-script-workaround).

**Comment by MichelleMa8** [comment]
Thank you for your suggestion. I'll explore the fpdf2. 

Thanks again for your time and your great work on this project!
